# Generated by Django 4.1.7 on 2023-02-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_auth.customer')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_auth.staff')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-id'],
            },
        ),
    ]
