# Generated by Django 4.2.1 on 2023-05-10 03:24

from django.db import migrations, models
import module.post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mod',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=module.post.models.img_dest),
        ),
    ]
