# Generated by Django 4.2.1 on 2023-05-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0001_initial'),
        ('post', '0002_remove_post_mod_post_desc_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_auth.staff'),
            preserve_default=False,
        ),
    ]
