# Generated by Django 4.1.7 on 2023-02-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='post_category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
