# Generated by Django 4.1.7 on 2023-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_options_alter_tag_post_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag_post',
            table='tags_posts',
        ),
    ]
