# Generated by Django 4.2 on 2023-04-21 03:41

from django.db import migrations, models
import module.image_content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=module.image_content.models.img_dest)),
            ],
        ),
    ]
