# Generated by Django 4.2 on 2023-04-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_content', '0002_imagecontent_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagecontent',
            table='image_content',
        ),
    ]
