# Generated by Django 4.1.7 on 2023-02-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag_post',
            options={'ordering': ['-id']},
        ),
    ]
