# Generated by Django 4.1.7 on 2023-02-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-id']},
        ),
    ]
